name: Build

on:
  push:
    branches-ignore:
      - experimental/**
      - master
  pull_request:
    branches-ignore:
      - experimental/**
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.51.1-noble
      options: --user 1001

    steps:
      - uses: brdgm/github-action-build@feature/playwright
        with:
          sonar-token: ${{ secrets.SONARCLOUD_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          playwright: true
