name: Build

on:
  push:
    branches-ignore:
      - experimental/**
  pull_request:
    branches-ignore:
      - experimental/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm install
    - run: npm run test:unit
    - run: npm run build
